name = "kuramoto-basin-scaling"
version = "0.1.0"

[[lean_lib]]
name = "KuramotoBasinScaling"
srcDir = "."
roots = [
  "Kuramoto.lean",
  "BasinVolume.lean",
  "ScalingLaws.lean",
  "EffectiveDOF.lean",
  "Examples.lean",
  "PhaseSpaceCurvature.lean",
  "Kuramoto3.lean"
]

[scripts]
run_examples = "lean --run Examples.lean"
run_kuramoto3 = "lean --run Kuramoto3.lean"